from pathlib import Path

from app.config import settings
from app.okf import frontmatter as fm

BUNDLE_ROOT = settings.bundle_path


class UnsafeConceptIdError(ValueError):
    """Raised when an LLM-provided concept_id would write outside the bundle root."""


def concept_path(concept_id: str) -> Path:
    """concept_id like 'professional/people/piyal' -> data/bundle/professional/people/piyal.md

    Validated so a stray '..', a leading '/', or a backslash in an LLM-produced
    concept_id can never cause a write outside BUNDLE_ROOT."""
    if not concept_id or ".." in concept_id.split("/") or "\\" in concept_id:
        raise UnsafeConceptIdError(f"Rejected unsafe concept_id: {concept_id!r}")

    candidate = (BUNDLE_ROOT / f"{concept_id}.md").resolve()

    try:
        candidate.relative_to(BUNDLE_ROOT)
    except ValueError:
        raise UnsafeConceptIdError(f"Rejected concept_id outside bundle root: {concept_id!r}")

    return candidate


def concept_exists(concept_id: str) -> bool:
    return concept_path(concept_id).exists()


def list_concepts() -> list[dict]:
    """Scan the whole bundle for existing concepts, so the extraction prompt can
    reuse a concept_id instead of drifting into a near-duplicate on every message."""
    if not BUNDLE_ROOT.exists():
        return []

    concepts = []
    for path in BUNDLE_ROOT.rglob("*.md"):
        if path.name in ("index.md", "log.md"):
            continue
        post = fm.load(path)
        if post is None:
            continue
        concept_id = path.relative_to(BUNDLE_ROOT).with_suffix("").as_posix()
        concepts.append({
            "concept_id": concept_id,
            "title": post.get("title", path.stem),
            "type": post.get("type", "Unknown"),
        })
    return concepts


def list_index_files() -> list[dict]:
    """Read every index.md in the bundle - a folder-level table of contents
    (regenerated by rebuild_index() on every write). Gives the extraction
    prompt a broad "what categories/areas exist" overview, complementing the
    specific top-K concept matches from retrieval.py rather than replacing them."""
    if not BUNDLE_ROOT.exists():
        return []

    indexes = []
    for path in BUNDLE_ROOT.rglob("index.md"):
        content = path.read_text().strip()
        if not content:
            continue
        folder = path.parent.relative_to(BUNDLE_ROOT).as_posix()
        indexes.append({"folder": folder or "(root)", "content": content})
    return indexes


def find_similar_concept(type_: str, title: str, threshold: int = 85) -> str | None:
    """Safety net against duplicate concepts: before a NEW file is created,
    fuzzy-match its title against existing concepts of the same type. If a
    close match exists, return its concept_id so the caller can reuse that
    file instead of forking a new one.

    This exists because the LLM does not always call search_concepts before
    deciding a concept - especially Tasks - is new. Prompting alone cannot
    guarantee that, so this is a code-level guardrail on top of it.
    """
    from rapidfuzz import fuzz

    candidates = [c for c in list_concepts() if c["type"] == type_]
    best_match = None
    best_score = 0
    for c in candidates:
        score = fuzz.ratio(title.lower(), c["title"].lower())
        if score > best_score:
            best_score = score
            best_match = c["concept_id"]

    if best_score >= threshold:
        return best_match
    return None


def write_concept(concept_id: str, type_: str, title: str, description: str, body_addition: str) -> tuple[Path, str]:
    """Create the concept file if missing, otherwise append to it. Returns (path, action)."""
    path = concept_path(concept_id)
    existing = fm.load(path)

    if existing is None:
        post = fm.new_post(type_, title, description, body_addition.strip() + "\n")
        action = "created"
    else:
        post = existing
        # Backfill any metadata missing from a prior partial/broken write -
        # never overwrites values that are already present.
        post.metadata.setdefault("type", type_)
        post.metadata.setdefault("title", title)
        post.metadata.setdefault("description", description)
        fm.append_body(post, body_addition)
        action = "updated"

    fm.save(post, path)
    return path, action


def add_link(concept_id: str, link_line: str) -> None:
    """Append a one-line cross-link into an existing concept's body, avoiding duplicates."""
    path = concept_path(concept_id)
    post = fm.load(path)
    if post is None:
        return
    if link_line.strip() in post.content:
        return
    fm.append_body(post, link_line)
    fm.save(post, path)


def add_relation(concept_id: str, predicate: str, target_concept_id: str) -> None:
    """Set a typed frontmatter relation (Vault-LD wikilink) on an existing concept,
    pointing at another concept by its full concept_id. This is the machine-readable
    counterpart to add_link()'s human-readable body cross-link.

    NOTE: 'relations' is meant for stable structural graph edges only
    (assignedTo, partOf, attendee, etc). Status/state information (e.g. a task
    being complete) should NOT be expressed as a relation - it belongs in the
    concept's body content as prose. This is enforced via the system prompt,
    not here; this function stays a plain, unconditional setter so its
    behavior doesn't depend on guessing which predicate names carry status
    meaning.
    """
    path = concept_path(concept_id)
    post = fm.load(path)
    if post is None:
        return
    fm.set_relation(post, predicate, target_concept_id)
    fm.save(post, path)

def get_title(concept_id: str) -> str | None:
    """Look up a concept's display title by its concept_id. Used when
    auto-generating a cross-link to a concept outside the current batch
    (so the link text isn't just the raw concept_id)."""
    if not concept_exists(concept_id):
        return None
    post = fm.load(concept_path(concept_id))
    return post.get("title", concept_id) if post else None


def remove_relation(concept_id: str, predicate: str, target_concept_id: str) -> None:
    """Remove one target from a typed frontmatter relation, if present. Handles
    both the single-string and list forms set_relation() can produce. No-op if
    the concept, predicate, or target isn't there.

    Kept as a general-purpose utility even though add_relation() no longer
    calls it automatically - useful for any future cleanup path (e.g. an
    unassign action) that needs to remove a specific relation edge.
    """
    path = concept_path(concept_id)
    post = fm.load(path)
    if post is None:
        return

    existing = post.get(predicate)
    if existing is None:
        return

    wikilink = f"[[{target_concept_id}]]"

    if isinstance(existing, list):
        if wikilink in existing:
            existing.remove(wikilink)
            if len(existing) == 1:
                post[predicate] = existing[0]   # demote back to a single string
            elif len(existing) == 0:
                del post[predicate]
            fm.touch_timestamp(post)
            fm.save(post, path)
    else:
        if existing == wikilink:
            del post[predicate]
            fm.touch_timestamp(post)
            fm.save(post, path)


def append_log(concept_id: str, entry: str) -> None:
    """Append a dated log entry to the log.md nearest the concept (its parent directory)."""
    scope_dir = concept_path(concept_id).parent
    scope_dir.mkdir(parents=True, exist_ok=True)
    log_path = scope_dir / "log.md"
    date_heading = fm.now_iso()[:10]  # YYYY-MM-DD

    if log_path.exists():
        text = log_path.read_text()
    else:
        text = "# Directory Update Log\n"

    heading = f"## {date_heading}"
    line = f"* {entry}"
    if heading in text:
        text = text.replace(heading, f"{heading}\n{line}", 1)
    else:
        text += f"\n{heading}\n{line}\n"

    log_path.write_text(text)


def get_related_concepts(concept_id: str) -> list[dict]:
    """Return concepts this concept has typed frontmatter relations to
    (e.g. assignedTo, hasTask, partOf) - a 1-hop graph lookup, used by the
    get_related_concepts tool so the model can see existing relationships
    before adding new ones."""
    path = concept_path(concept_id)
    post = fm.load(path)
    if post is None:
        return [{"info": f"No concept found at {concept_id}"}]

    reserved_keys = {"type", "title", "description", "timestamp"}
    related = []
    for key, value in post.metadata.items():
        if key in reserved_keys:
            continue
        values = value if isinstance(value, list) else [value]
        for v in values:
            if isinstance(v, str) and v.startswith("[[") and v.endswith("]]"):
                target_id = v[2:-2]
                target_post = fm.load(concept_path(target_id)) if concept_exists(target_id) else None
                related.append({
                    "predicate": key,
                    "concept_id": target_id,
                    "title": target_post.get("title", target_id) if target_post else target_id,
                    "type": target_post.get("type", "Unknown") if target_post else "Unknown",
                })
    return related or [{"info": f"{concept_id} has no recorded relations yet."}]


def rebuild_index(directory: Path) -> None:
    """Regenerate index.md for a directory by scanning its concept files' frontmatter."""
    entries = []
    for path in sorted(directory.glob("*.md")):
        if path.name in ("index.md", "log.md"):
            continue
        post = fm.load(path)
        if post is None:
            continue
        title = post.get("title", path.stem)
        desc = post.get("description", "")
        entries.append(f"* [{title}]({path.name}) - {desc}" if desc else f"* [{title}]({path.name})")

    subdirs = [p for p in directory.iterdir() if p.is_dir()]

    lines = ["# Index\n"]
    if entries:
        lines.append("## Concepts\n")
        lines.extend(entries)
        lines.append("")
    if subdirs:
        lines.append("## Subdirectories\n")
        lines.extend(f"* [{d.name}/]({d.name}/)" for d in sorted(subdirs))
        lines.append("")

    (directory / "index.md").write_text("\n".join(lines))